name = "Blackwater Bay"

[domain]
start_time = "2021-01-01 00:00:00"
stop_time = "2021-01-02 00:00:00"
grid_size_x = 120
grid_size_y = 80

[spectrum]
num_frequencies = 37
num_directions = 36
frequency_min = 0.0313
frequency_max = 2.0
