program umwm_topogen

  ! Topography generation utility for UMWM. Reads UMWM input
  ! grid file and ETOPO topography field. Outputs grid and topography
  ! in NetCDF format (umwm.gridtopo) that can be used by the wave model. 

  use netcdf
  use umwm_utils, only: nc_check

  implicit none

  integer :: i, j, i0, j0
  logical :: useSeamask
  integer :: ncid, xdimid, ydimid, lonid, latid, zid, maskid

  character(NF90_MAX_NAME) :: dimname

  character(9999) :: topoInputFile, umwmInputFile

  type :: grid
    integer :: idm, jdm
    real, allocatable :: lon1d(:), lat1d(:)
    real, allocatable :: lon(:,:), lat(:,:), z(:,:)
  end type grid 

  type(grid) :: topo, umwm

  integer, allocatable :: mask(:,:)

  namelist /topogen/ umwmInputFile, topoInputFile, useSeamask

  ! 1) Read namelist:
  open(10, file='namelists/topogen.nml', status='old', &
       form='formatted', access='sequential')
  read(10, nml=topogen)
  close(10)

  ! 2) Read input grid:
  print *, 'umwm_topogen: Reading input (UMWM) grid.'

  call nc_check(nf90_open(trim(umwmInputFile), nf90_nowrite, ncid))
  call nc_check(nf90_inq_dimid(ncid, 'x', xdimid))
  call nc_check(nf90_inq_dimid(ncid, 'y', ydimid))
  call nc_check(nf90_inquire_dimension(ncid, xdimid, dimname, umwm % idm))
  call nc_check(nf90_inquire_dimension(ncid, ydimid, dimname, umwm % jdm))

  allocate(umwm % lon(umwm % idm, umwm % jdm))
  allocate(umwm % lat(umwm % idm, umwm % jdm))
  allocate(umwm % z(umwm % idm, umwm % jdm))

  if (useSeamask) allocate(mask(umwm % idm, umwm % jdm))

  call nc_check(nf90_inq_varid(ncid, 'lon', lonid))
  call nc_check(nf90_inq_varid(ncid, 'lat', latid))
  call nc_check(nf90_get_var(ncid, lonid, umwm % lon))
  call nc_check(nf90_get_var(ncid, latid, umwm % lat))

  if(useSeamask)THEN
    call nc_check(nf90_inq_varid(ncid, 'seamask', maskid))
    call nc_check(nf90_get_var(ncid, maskid, mask))
  endif

  call nc_check(nf90_close(ncid))

  ! 3) Read ETOPO01 grid and topography:
  WRITE(*, *)'umwm_topogen: Reading input topography data.'

  call nc_check(nf90_open(trim(topoInputFile), nf90_nowrite, ncid))
  call nc_check(nf90_inq_dimid(ncid, 'lon', xdimid))
  call nc_check(nf90_inq_dimid(ncid, 'lat', ydimid))
  call nc_check(nf90_inquire_dimension(ncid, xdimid, dimname, topo % idm))
  call nc_check(nf90_inquire_dimension(ncid, ydimid, dimname, topo % jdm))

  allocate(topo % lon1d(topo % idm))
  allocate(topo % lat1d(topo % jdm))
  allocate(topo % z(topo % idm, topo % jdm))

  ! Uncomment for ETOPO
  !call nc_check(nf90_inq_varid(ncid, 'x', lonid))
  !call nc_check(nf90_inq_varid(ncid, 'y', latid))
  !call nc_check(nf90_inq_varid(ncid, 'z', zid))

  ! Uncommend for GEBCO
  call nc_check(nf90_inq_varid(ncid, 'lon', lonid))
  call nc_check(nf90_inq_varid(ncid, 'lat', latid))
  call nc_check(nf90_inq_varid(ncid, 'elevation', zid))

  call nc_check(nf90_get_var(ncid, lonid, topo % lon1d))
  call nc_check(nf90_get_var(ncid, latid, topo % lat1d))
  call nc_check(nf90_get_var(ncid, zid, topo % z))

  call nc_check(nf90_close(ncid))

  ! 4) Loop over target (UMWM) grid and sample ETOPO01 values:
  print *, 'umwm_topogen: Sampling topography on target grid.'

  do j = 1, umwm % jdm
    print *, 'umwm_topogen: Sampling row', j
    do i = 1, umwm % idm
      i0 = minloc(abs(umwm % lon(i,j)-topo % lon1d), dim=1)
      j0 = minloc(abs(umwm % lat(i,j)-topo % lat1d), dim=1)
      umwm % z(i,j) = topo % z(i0,j0)
    enddo
  enddo

  ! Adjust bathymetry to match the input seamask:
  if (useSeamask) then
    where (mask == 0 .and. umwm % z < 0) umwm % z = 0
    where (mask == 1 .and. umwm % z >= 0) umwm % z = -100
  end if

  ! 5) Generate new umwm.gridtopo file:
  print *, 'umwm_topogen: Writing umwm.gridtopo file.'

  call nc_check(nf90_create('umwm.gridtopo', nf90_clobber, ncid))
  call nc_check(nf90_def_dim(ncid, 'x', umwm % idm, xdimid))
  call nc_check(nf90_def_dim(ncid, 'y', umwm % jdm, ydimid))
  call nc_check(nf90_def_var(ncid, 'lon', nf90_float, [xdimid, ydimid], lonid))
  call nc_check(nf90_def_var(ncid, 'lat', nf90_float, [xdimid, ydimid], latid))
  if(useSeamask)call nc_check(nf90_def_var(ncid, 'seamask', nf90_int, [xdimid, ydimid], maskid))
  call nc_check(nf90_def_var(ncid, 'z', nf90_float, [xdimid, ydimid], zid))
  call nc_check(nf90_put_att(ncid, NF90_GLOBAL, name='history', values='Generated by umwm_topogen'))
  call nc_check(nf90_enddef(ncid))
  call nc_check(nf90_put_var(ncid, lonid, umwm % lon))
  call nc_check(nf90_put_var(ncid, latid, umwm % lat))
  if (useSeamask) call nc_check(nf90_put_var(ncid, maskid, mask))
  call nc_check(nf90_put_var(ncid, zid, umwm % z))
  call nc_check(nf90_close(ncid))

  print *, 'umwm_topogen: Success.'

end program umwm_topogen
